apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-pushgateway
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: prometheus-pushgateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: prometheus-pushgateway
    spec:
      containers:
      - image: quay.io/prometheus/pushgateway:v1.6.2
        imagePullPolicy: IfNotPresent
        name: container
        ports:
        - containerPort: 9091
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
